# -*- coding: utf-8 -*-
"""get_unique.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jVRCsFjoYLsOcxAgnV3705XPYJZKjrx6
"""

# Mount Google Drive to Google Colab

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

# Libraries import

import pandas as pd

FNR_file=pd.read_csv("/content/drive/MyDrive/Iftach lab members/Shira Artman/Phage display - peptides/NGS/210922 Illumina run - analysis/nucleotides/F3_nucs.csv")
Cyt_file=pd.read_csv("/content/drive/MyDrive/Iftach lab members/Shira Artman/Phage display - peptides/NGS/210922 Illumina run - analysis/nucleotides/C3_nucs.csv")
Thy_file=pd.read_csv("/content/drive/MyDrive/Iftach lab members/Shira Artman/Phage display - peptides/NGS/210922 Illumina run - analysis/nucleotides/T3_nucs.csv")

unique_FNR_vs_Cyt=FNR_file.loc[~FNR_file['nuc_seq'].isin(Cyt_file['nuc_seq']), 'nuc_seq']
# peptides that exist only in FNR and not in Cyt
unique_FNR=unique_FNR_vs_Cyt.loc[~unique_FNR_vs_Cyt.isin(Thy_file['nuc_seq'])]
# peptides that exist only in FNR and not in Cyt nor Thy